[project]
name = 'ElderMedChain-Management-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.caregiver-coordination-network]
path = 'contracts/caregiver-coordination-network.clar'
clarity_version = 3
epoch = '3.2'

[contracts.drug-interaction-monitoring]
path = 'contracts/drug-interaction-monitoring.clar'
clarity_version = 3
epoch = '3.2'

[contracts.medication-adherence-rewards]
path = 'contracts/medication-adherence-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.medication-schedule-registry]
path = 'contracts/medication-schedule-registry.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
